OPENQASM 3.0;
include "qelib1.inc";

// E91 Quantum Key Distribution Protocol (Ekert protocol)
// Uses entangled qubit pairs and Bell inequality violation for security

// Qubits: 
//   0 - Alice's qubit (from entangled pair)
//   1 - Bob's qubit (from entangled pair)
//   We assume entangled pairs are generated by a source and distributed to Alice and Bob

qubit[2] q;

// Classical bits for measurement basis choices and results
bit[2] alice_basis; // 0, 1, 2 for three measurement bases
bit[2] bob_basis;   // 0, 1, 2 for three measurement bases
bit[2] alice_bit;   // Alice's measurement result (0 or 1)
bit[2] bob_bit;     // Bob's measurement result (0 or 1)

// Prepare entangled pair: |Φ⁺> = (|00> + |11>)/√2
// We'll create this by applying H to first qubit then CNOT
h q[0];
cx q[0], q[1];

// Alice chooses measurement basis randomly (0, 1, 2)
// For simplicity in this example, we fix Alice's basis to 0
// In a full simulation, we would randomize and then sift

// Bob chooses measurement basis randomly (0, 1, 2)
// For simplicity, we fix Bob's basis to 0

// Define measurement bases:
// Basis 0: Z basis (|0>, |1>)
// Basis 1: X basis (|+>, |->)
// Basis 2: Y basis (|i>, |-i>)

// Apply basis rotation before measurement
// For Alice
if (alice_basis[0] == 1) {
    h q[0]; // X basis
} else if (alice_basis[0] == 2) {
    sxdg q[0]; // Y basis: S† then H
    h q[0];
}

// For Bob
if (bob_basis[0] == 1) {
    h q[1]; // X basis
} else if (bob_basis[0] == 2) {
    sxdg q[1]; // Y basis
    h q[1];
}

// Measure both qubits
measure q[0] -> alice_bit[0];
measure q[1] -> bob_bit[0];

// In a full E91 protocol:
// 1. Many entangled pairs are generated and distributed
// 2. Alice and Bob each randomly choose a basis for each qubit
// 3. They measure and record results
// 4. They publicly announce their basis choices (but not results)
// 5. They keep only the results where bases matched (or are correlated for E91)
// 6. They use a subset to test Bell inequality (CHSH)
// 7. If Bell inequality is violated, they proceed with error correction and privacy amplification
// 8. Otherwise, they abort due to potential eavesdropping

// End of circuit